<?php

/**
 * This is the model base class for the table "user_verification".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserVerification".
 *
 * Columns in table "user_verification" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_verification
 * @property integer $id_user
 *
 */
abstract class BaseUserVerification extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_verification';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserVerification|UserVerifications', $n);
	}

	public static function representingColumn() {
		return array(
			'id_verification',
			'id_user',
		);
	}

	public function rules() {
		return array(
			array('id_verification, id_user', 'required'),
			array('id_verification, id_user', 'numerical', 'integerOnly'=>true),
			array('id_verification, id_user', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_verification' => null,
			'id_user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_verification', $this->id_verification);
		$criteria->compare('id_user', $this->id_user);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}